---
title: "Data Visualization Notes"
author: "Nick Palmer"
date: "2022-04-12"
output: html_document
---
   
Project Proposal
    For our team project, we decided to compile data from the real estate market and look into the different variables affecting housing prices. Using the knowledge learned from our data analytics courses we will be constructing various models in order to better understand trends in real estate and how the markets in different areas around the country differ. Utilizing R Studio, we will be able to visualize this data using the ggplot2 package by building graphs of these models. The main thing we are trying to test and visualize is how the location of a home affects its price taking into account the home's features. We expect to see states with higher tax rates, such as New York, to have more expensive homes than those with lower tax rates. 
In order to get reliable data to study the test variables, we compiled a dataset that has 160+ individual homes varying in location throughout the United States. We were able to extract the data from Zillow.com, which is a reliable and up to date source to make sure our data is accurate. We extracted all of the data in our set entirely from Zillow.com, regardless of the variable. 
The results we find will allow us to compare the differences in pricing between states, which is very valuable when it comes to selecting possible residency in the future. Our models will properly visualize the distinct differences amongst regions and how the homes are valued. Given our null hypothesis which was stated prior, we expect to find New York as the most expensive state to live in, given consistent features in the homes. We are excited to present our results and deliver our findings in an accessible way to help project the differences between the state's housing values. 
